import './livingroom.css';

const LIVING = {
  room: 'living',
  backgroundImage: '/assets/images/pictures/1F/LIVINGROOM-POINTED.png',
  items: [
    {
      itemImage: '/assets/images/pictures/1F/pointers-livingroom/console.gif',
      itemPosition: { x: '1103px', y: '363px' },
      itemSound: '/assets/audio/sounds/rooms/tv-switching.mp3',
      colliderSize: { w: '235px', h: '150px' },
      colliderPosition: { x: '1104px', y: '377px' },
      size: '245px',
      hiddenOnPrint: true,
      disappearOnClick: true,
    },
    {
      itemImage: '/assets/images/pictures/1F/pointers-livingroom/drawer.png',
      itemPosition: { x: '452px', y: '579px' },
      itemSound: '/assets/audio/sounds/rooms/drawer.mp3',
      colliderSize: { w: '181px', h: '45px' },
      colliderPosition: { x: '452px', y: '579px' },
      size: '181px',
      hiddenOnPrint: true,
      disappearOnClick: false,
    },
    {
      itemImage: '/assets/images/pictures/1F/pointers-livingroom/books.png',
      itemPosition: { x: '1127px', y: '791px' },
      itemSound: '/assets/audio/sounds/rooms/leaves.mp3',
      colliderSize: { w: '140px', h: '35px' },
      colliderPosition: { x: '1127px', y: '791px' },
      size: '157px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: '/assets/images/pictures/1F/pointers-livingroom/box.png',
      itemPosition: { x: '1553px', y: '725px' },
      itemSound: '/assets/audio/sounds/rooms/toolbox.mp3',
      colliderSize: { w: '187px', h: '50px' },
      colliderPosition: { x: '1553px', y: '725px' },
      size: '208px',
      hiddenOnPrint: false,
      disappearOnClick: true,
    },
    {
      itemImage: '/assets/images/pictures/1F/pointers-livingroom/layer-comode.png',
      itemPosition: { x: '877px', y: '511px' },
      itemSound: '/assets/audio/sounds/rooms/paint.mp3',
      colliderSize: { w: '61px', h: '70px' },
      colliderPosition: { x: '877px', y: '511px' },
      size: '61px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: '/assets/images/pictures/1F/pointers-livingroom/little-picture.png',
      itemPosition: { x: '483px', y: '368px' },
      itemSound: '/assets/audio/sounds/rooms/paint.mp3',
      colliderSize: { w: '33px', h: '51px' },
      colliderPosition: { x: '483px', y: '368px' },
      size: '33px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: '/assets/images/pictures/1F/pointers-livingroom/metal-block.png',
      itemPosition: { x: '550px', y: '194px' },
      itemSound: '/assets/audio/sounds/rooms/metal-drag.mp3',
      colliderSize: { w: '47px', h: '90px' },
      colliderPosition: { x: '550px', y: '194px' },
      size: '47px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: '/assets/images/pictures/1F/pointers-livingroom/camera.png',
      itemPosition: { x: '0px', y: '413px' },
      itemSound: '/assets/audio/sounds/rooms/drag-candle.mp3',
      colliderSize: { w: '103px', h: '50px' },
      colliderPosition: { x: '0px', y: '413px' },
      size: '103px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: '/assets/images/pictures/1F/pointers-livingroom/picture-wall.png',
      itemPosition: { x: '1184px', y: '284px' },
      itemSound: '/assets/audio/sounds/rooms/sliding-wood.mp3',
      colliderSize: { w: '41px', h: '60px' },
      colliderPosition: { x: '1184px', y: '284px' },
      size: '41px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: '/assets/images/pictures/1F/pointers-livingroom/ticket.png',
      itemPosition: { x: '264px', y: '723px' },
      itemSound: '/assets/audio/sounds/rooms/searching.mp3',
      colliderSize: { w: '288px', h: '70px' },
      colliderPosition: { x: '264px', y: '718px' },
      size: '288px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: '/assets/images/pictures/1F/pointers-livingroom/under-couch.png',
      itemPosition: { x: '346px', y: '908px' },
      itemSound: '/assets/audio/sounds/rooms/paint.mp3',
      colliderSize: { w: '135px', h: '70px' },
      colliderPosition: { x: '346px', y: '908px' },
      size: '135px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: '/assets/images/pictures/1F/pointers-livingroom/note.png',
      itemPosition: { x: '1591px', y: '38.5px' },
      itemSound: '/assets/audio/sounds/rooms/story-note.mp3',
      colliderSize: { w: '21px', h: '20px' },
      colliderPosition: { x: '1625px', y: '59px' },
      size: '64px',
      hiddenOnPrint: false,
      disappearOnClick: true,
    },
  ],
};

export default LIVING;
