import './livingroom.css';

const LIVING = {
  room: 'living',
  backgroundImage: 'src/assets/images/pictures/1F/LIVINGROOM-POINTED.png',
  items: [
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/console.gif',
      itemPosition: { x: '646px', y: '565px' },
      itemSound: 'src/assets/audio/sounds/rooms/tv-switching.mp3',
      colliderSize: { w: '183px', h: '140px' },
      colliderPosition: { x: '650px', y: '568px' },
      size: '183px',
      hiddenOnPrint: true,
      disappearOnClick: true,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/ticket.png',
      itemPosition: { x: '452px', y: '579px' },
      itemSound: 'src/assets/audio/sounds/rooms/metal-drag.mp3',
      colliderSize: { w: '181px', h: '45px' },
      colliderPosition: { x: '452px', y: '579px' },
      size: '181px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/books.png',
      itemPosition: { x: '1127px', y: '791px' },
      itemSound: 'src/assets/audio/sounds/rooms/door-creaks.mp3',
      colliderSize: { w: '140px', h: '35px' },
      colliderPosition: { x: '1127px', y: '791px' },
      size: '157px',
      hiddenOnPrint: true,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/box.png',
      itemPosition: { x: '1553px', y: '725px' },
      itemSound: 'src/assets/audio/sounds/rooms/toolbox.mp3',
      colliderSize: { w: '187px', h: '50px' },
      colliderPosition: { x: '1553px', y: '725px' },
      size: '208px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/layer-comode.png',
      itemPosition: { x: '877px', y: '511px' },
      itemSound: 'src/assets/audio/sounds/rooms/drag-bottle.mp3',
      colliderSize: { w: '61px', h: '70px' },
      colliderPosition: { x: '877px', y: '511px' },
      size: '61px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/little-picture.png',
      itemPosition: { x: '483px', y: '368px' },
      itemSound: 'src/assets/audio/sounds/rooms/drag-bottle.mp3',
      colliderSize: { w: '33px', h: '51px' },
      colliderPosition: { x: '483px', y: '368px' },
      size: '33px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/metal-block.png',
      itemPosition: { x: '550px', y: '194px' },
      itemSound: 'src/assets/audio/sounds/rooms/toolbox.mp3',
      colliderSize: { w: '47px', h: '90px' },
      colliderPosition: { x: '550px', y: '194px' },
      size: '47px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/camera.png',
      itemPosition: { x: '0px', y: '413px' },
      itemSound: 'src/assets/audio/sounds/rooms/sliding-wood.mp3',
      colliderSize: { w: '103px', h: '50px' },
      colliderPosition: { x: '0px', y: '413px' },
      size: '103px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/picture-wall.png',
      itemPosition: { x: '1184px', y: '284px' },
      itemSound: 'src/assets/audio/sounds/rooms/sliding-wood.mp3',
      colliderSize: { w: '41px', h: '61px' },
      colliderPosition: { x: '1184px', y: '284px' },
      size: '41px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/switch-on.png',
      itemPosition: { x: '688px', y: '955px' },
      itemSound: 'src/assets/audio/sounds/rooms/searching.mp3',
      colliderSize: { w: '71px', h: '35px' },
      colliderPosition: { x: '688px', y: '955px' },
      size: '71px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/switch-off.png',
      itemPosition: { x: '1160px', y: '412px' },
      itemSound: 'src/assets/audio/sounds/rooms/paint.mp3',
      colliderSize: { w: '79px', h: '62px' },
      colliderPosition: { x: '1171px', y: '424px' },
      size: '95px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/under-couch.png',
      itemPosition: { x: '1160px', y: '412px' },
      itemSound: 'src/assets/audio/sounds/rooms/paint.mp3',
      colliderSize: { w: '79px', h: '62px' },
      colliderPosition: { x: '1171px', y: '424px' },
      size: '95px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-livingroom/note.png',
      itemPosition: { x: '1597px', y: '47px' },
      itemSound: 'src/assets/audio/sounds/rooms/story-note.mp3',
      colliderSize: { w: '21px', h: '20px' },
      colliderPosition: { x: '1632px', y: '68px' },
      size: '64px',
      hiddenOnPrint: false,
      disappearOnClick: true,
    },
  ],
};

export default LIVING;
