import './Kitchen.css';

const KITCHEN = {
  room: 'kitchen',
  backgroundImage: 'src/assets/images/pictures/1F/KITCHEN-POINTED.png',
  items: [
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-kitchen/console.gif',
      itemPosition: { x: '646px', y: '565px' },
      itemSound: 'src/assets/audio/sounds/rooms/tv-switching.mp3',
      colliderSize: { w: '183px', h: '140px' },
      colliderPosition: { x: '650px', y: '568px' },
      size: '183px',
      hiddenOnPrint: true,
      disappearOnClick: true,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-kitchen/ticket.png',
      itemPosition: { x: '1808px', y: '736px' },
      itemSound: 'src/assets/audio/sounds/rooms/metal-drag.mp3',
      colliderSize: { w: '76px', h: '30px' },
      colliderPosition: { x: '1808px', y: '736px' },
      size: '76px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-kitchen/above-tv.png',
      itemPosition: { x: '751px', y: '477px' },
      itemSound: 'src/assets/audio/sounds/rooms/door-creaks.mp3',
      colliderSize: { w: '92px', h: '58px' },
      colliderPosition: { x: '751px', y: '477px' },
      size: '92px',
      hiddenOnPrint: true,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-kitchen/drawer.png',
      itemPosition: { x: '269px', y: '637px' },
      itemSound: 'src/assets/audio/sounds/rooms/toolbox.mp3',
      colliderSize: { w: '139px', h: '78px' },
      colliderPosition: { x: '269px', y: '637px' },
      size: '139px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-kitchen/mess.png',
      itemPosition: { x: '1584px', y: '220px' },
      itemSound: 'src/assets/audio/sounds/rooms/drag-bottle.mp3',
      colliderSize: { w: '53px', h: '48px' },
      colliderPosition: { x: '1584px', y: '220px' },
      size: '53px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-kitchen/pan.png',
      itemPosition: { x: '1413px', y: '599px' },
      itemSound: 'src/assets/audio/sounds/rooms/drag-bottle.mp3',
      colliderSize: { w: '58px', h: '45px' },
      colliderPosition: { x: '1413px', y: '599px' },
      size: '58px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-kitchen/sarten.png',
      itemPosition: { x: '1704px', y: '377px' },
      itemSound: 'src/assets/audio/sounds/rooms/toolbox.mp3',
      colliderSize: { w: '50px', h: '110px' },
      colliderPosition: { x: '1704px', y: '377px' },
      size: '40px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-kitchen/shield.png',
      itemPosition: { x: '312px', y: '236px' },
      itemSound: 'src/assets/audio/sounds/rooms/sliding-wood.mp3',
      colliderSize: { w: '59px', h: '115px' },
      colliderPosition: { x: '312px', y: '236px' },
      size: '59px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-kitchen/tea.png',
      itemPosition: { x: '1063px', y: '641px' },
      itemSound: 'src/assets/audio/sounds/rooms/sliding-wood.mp3',
      colliderSize: { w: '65px', h: '45px' },
      colliderPosition: { x: '1063px', y: '641px' },
      size: '70px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-kitchen/under.png',
      itemPosition: { x: '688px', y: '955px' },
      itemSound: 'src/assets/audio/sounds/rooms/searching.mp3',
      colliderSize: { w: '71px', h: '35px' },
      colliderPosition: { x: '688px', y: '955px' },
      size: '71px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-kitchen/wall-hatch.png',
      itemPosition: { x: '1160px', y: '412px' },
      itemSound: 'src/assets/audio/sounds/rooms/paint.mp3',
      colliderSize: { w: '79px', h: '62px' },
      colliderPosition: { x: '1171px', y: '424px' },
      size: '95px',
      hiddenOnPrint: false,
      disappearOnClick: false,
    },
    {
      itemImage: 'src/assets/images/pictures/1F/pointers-kitchen/note.png',
      itemPosition: { x: '983px', y: '245.5px' },
      itemSound: 'src/assets/audio/sounds/rooms/story-note.mp3',
      colliderSize: { w: '14px', h: '48px' },
      colliderPosition: { x: '1066px', y: '284.5px' },
      size: '113px',
      hiddenOnPrint: false,
      disappearOnClick: true,
    },
  ],
};

export default KITCHEN;
